### ISSUE TITLE
RAM DOS

### ISSUE THREAD

**Issue by singpolyma** [aaronpk/Switchboard#5]
I am concerned about https://github.com/aaronpk/Switchboard/blob/master/lib/PushTask.php#L88 -- specifically, about how it seems to slurp the full content of a topic URL into RAM without any limit on size (unless such limit is automatically provided by cURL, but I haven't yet found indication that it is).

This means (I think) that anyone could place a many-gigabytes file at a topic URL and probably get parts of a webserver running Switchboard OOMkilled.

**Comment by aaronpk** [comment]
In practice this is enforced by the PHP process itself. PHP has a setting for a maximum memory limit, at which point the process will be killed. I'm not really interested in trying to solve this for real using some sort of stream solution, since the vast majority of content this is used for is relatively small pages.
